sudo: required
services:
  - docker

before_install:
  - docker build -t sakshibajaj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sakshibajaj/react-test npm test

after_success:
  - docker build -t bajajsakshi/multi-client ./client
  - docker build -t bajajsakshi/multi-nginx ./nginx
  - docker build -t bajajsakshi/multi-server ./server
  - docker build -t bajajsakshi/multi-worker ./worker

  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push it to docker hub
  - docker push bajajsakshi/multi-client
  - docker push bajajsakshi/multi-nginx
  - docker push bajajsakshi/multi-server
  - docker push bajajsakshi/multi-worker